export const EXECUTION_RUN_SCHEMA = "agentic-sdlc-run/v1";

export const EXECUTION_FINDING_TYPES = Object.freeze([
  "self-graded-verdict",
  "unnamed-evaluator",
  "ungrounded-task",
  "unexecuted-condition",
  "task-cycle",
  "concurrent-write-conflict",
  "parallel-scope-collision",
  "stale-collaboration-fence",
  "delivery-authority-unjoined",
  "canonical-base-drift",
  "scope-admission-collision",
  "unattributed-lane-ambiguity",
  "admission-snapshot-stale",
  "unsafe-candidate-target",
  "local-only-cross-device-lease",
  "collateral-lane-mutation",
  "admission-runtime-conflation",
  "candidate-lane-orphaned",
  "state-without-reason",
  "oversized-task",
  "unsurfaced-result",
  "unenumerated-change",
  "self-escalated-capability",
  "out-of-scope-write",
  "ungated-irreversible-operation",
  "unbounded-task",
  "budget-raised-under-pressure",
  "unrecorded-consumption",
  "fix-without-witness",
  "unproven-property",
  "evidence-without-run",
  "unresumable-run",
  "assumed-operator-decision",
  "unreviewed-release-candidate",
  "dependency-closure-drift",
  "authorization-evidence-unjoined",
  "authorization-interaction-unjoined",
  "duplicate-release-controller",
  "production-authorization-drift",
  "post-authorization-rebuild",
  "state-reconciliation-unverified",
  "immutable-origin-unverified",
  "public-route-unverified",
  "client-cache-convergence-unverified",
  "publication-before-live-verification",
  "cleanup-ownership-unproven",
  "integration-order-cycle",
  "integration-before-dependency",
  "canonical-frontier-unverified",
  "duplicate-change-reintegrated",
  "stale-candidate-frontier",
  "runtime-readiness-unproven",
  "undesigned-criterion",
  "ungrounded-design-element",
  "requirement-introduced-downstream",
  "stale-downstream-artifact",
  "phase-advanced-without-approval",
  "seam-elided",
]);

export const EXECUTION_FINDING_SEVERITIES = Object.freeze({
  "self-graded-verdict": "blocker",
  "unnamed-evaluator": "blocker",
  "ungrounded-task": "major",
  "unexecuted-condition": "major",
  "task-cycle": "blocker",
  "concurrent-write-conflict": "major",
  "parallel-scope-collision": "blocker",
  "stale-collaboration-fence": "blocker",
  "delivery-authority-unjoined": "blocker",
  "canonical-base-drift": "blocker",
  "scope-admission-collision": "blocker",
  "unattributed-lane-ambiguity": "blocker",
  "admission-snapshot-stale": "blocker",
  "unsafe-candidate-target": "blocker",
  "local-only-cross-device-lease": "blocker",
  "collateral-lane-mutation": "blocker",
  "admission-runtime-conflation": "major",
  "candidate-lane-orphaned": "major",
  "state-without-reason": "minor",
  "oversized-task": "minor",
  "unsurfaced-result": "major",
  "unenumerated-change": "minor",
  "self-escalated-capability": "blocker",
  "out-of-scope-write": "major",
  "ungated-irreversible-operation": "blocker",
  "unbounded-task": "blocker",
  "budget-raised-under-pressure": "major",
  "unrecorded-consumption": "minor",
  "fix-without-witness": "major",
  "unproven-property": "major",
  "evidence-without-run": "blocker",
  "unresumable-run": "major",
  "assumed-operator-decision": "blocker",
  "unreviewed-release-candidate": "blocker",
  "dependency-closure-drift": "blocker",
  "authorization-evidence-unjoined": "blocker",
  "authorization-interaction-unjoined": "blocker",
  "duplicate-release-controller": "blocker",
  "production-authorization-drift": "blocker",
  "post-authorization-rebuild": "blocker",
  "state-reconciliation-unverified": "blocker",
  "immutable-origin-unverified": "blocker",
  "public-route-unverified": "blocker",
  "client-cache-convergence-unverified": "blocker",
  "publication-before-live-verification": "blocker",
  "cleanup-ownership-unproven": "blocker",
  "integration-order-cycle": "blocker",
  "integration-before-dependency": "blocker",
  "canonical-frontier-unverified": "blocker",
  "duplicate-change-reintegrated": "major",
  "stale-candidate-frontier": "blocker",
  "runtime-readiness-unproven": "blocker",
  "undesigned-criterion": "major",
  "ungrounded-design-element": "minor",
  "requirement-introduced-downstream": "blocker",
  "stale-downstream-artifact": "major",
  "phase-advanced-without-approval": "blocker",
  "seam-elided": "blocker",
});

export const SEVERITY_RANK = Object.freeze({
  blocker: 0,
  major: 1,
  minor: 2,
});

export const EXECUTION_ROLES = Object.freeze([
  "orchestrator",
  "implementer",
  "evaluator",
  "operator",
]);

export const TASK_STATES = Object.freeze([
  "not-started",
  "queued",
  "ready",
  "in-progress",
  "verified",
  "failed",
  "blocked",
  "abandoned",
]);

export const TERMINAL_TASK_STATES = Object.freeze([
  "verified",
  "failed",
  "blocked",
  "abandoned",
]);

export const CAPABILITY_CLASSES = Object.freeze([
  "read",
  "local-write",
  "local-execute",
  "environment-mutate",
  "irreversible",
  "boundary-crossing",
]);

export const BUDGET_FIELDS = Object.freeze([
  "tokens",
  "iterations",
  "wallClockMs",
  "contextTokens",
]);

export const PROPERTY_CLASSES = Object.freeze([
  "round-trip",
  "invariant",
  "metamorphic",
  "idempotence",
  "confluence",
  "error-condition",
]);

export const TASK_ID_PATTERN = /^(?:[1-9]\d*)(?:\.(?:[1-9]\d*))?$/u;

export const EXACT_CIRCUIT_BREAKER_LIMIT = 2;

export const READINESS_LADDER = Object.freeze([
  "undocumented",
  "spec-complete",
  "dev-proven",
  "runtime-ready",
  "production-verified",
]);
