const RULE_IDS_BY_FINDING = Object.freeze({
  "assumed-operator-decision": ["human-in-the-loop-gates#2", "human-in-the-loop-gates#5"],
  "budget-raised-under-pressure": ["per-task-budgets#2"],
  "canonical-base-drift": ["validation-checklist#7"],
  "candidate-lane-orphaned": ["validation-checklist#7"],
  "cleanup-ownership-unproven": ["validation-checklist#35"],
  "client-cache-convergence-unverified": ["validation-checklist#43"],
  "collateral-lane-mutation": ["validation-checklist#7"],
  "concurrent-write-conflict": ["task-model#15"],
  "admission-runtime-conflation": ["runtime-readiness-enforcement#4"],
  "admission-snapshot-stale": ["validation-checklist#7"],
  "authorization-evidence-unjoined": ["validation-checklist#33"],
  "authorization-interaction-unjoined": ["validation-checklist#38"],
  "canonical-frontier-unverified": ["dependency-ordered-integration#9"],
  "dependency-closure-drift": [
    "runtime-readiness-enforcement#2",
    "validation-checklist#37",
  ],
  "deploy-boundary-breach": ["tool-permission--blast-radius#4", "tool-permission--blast-radius#5"],
  "duplicate-change-reintegrated": ["dependency-ordered-integration#2"],
  "duplicate-release-controller": ["validation-checklist#40"],
  "evidence-without-run": [
    "verification-strategy#10",
    "verification-strategy#11",
    "verification-strategy#12",
  ],
  "fix-without-witness": ["verification-strategy#3"],
  "immutable-origin-unverified": ["validation-checklist#43"],
  "integration-before-dependency": ["dependency-ordered-integration#3"],
  "integration-order-cycle": ["dependency-ordered-integration#3"],
  "local-only-cross-device-lease": ["validation-checklist#6"],
  "out-of-scope-write": ["tool-permission--blast-radius#6"],
  "oversized-task": [
    "task-model#1",
    "task-model#2",
    "task-model#10",
    "task-model#11",
    "task-model#12",
  ],
  "parallel-scope-collision": ["validation-checklist#6"],
  "post-authorization-rebuild": ["validation-checklist#41"],
  "production-authorization-drift": ["end-to-end-release-lifecycle-protocol#9"],
  "publication-before-live-verification": ["end-to-end-release-lifecycle-protocol#11"],
  "public-route-unverified": ["validation-checklist#43"],
  "runtime-readiness-unproven": ["runtime-readiness-enforcement#5"],
  "scope-admission-collision": ["validation-checklist#7"],
  "self-escalated-capability": ["tool-permission--blast-radius#1", "tool-permission--blast-radius#2"],
  "self-graded-verdict": ["agent-roles--independence#6", "agent-roles--independence#8"],
  "stale-evidence": ["boundary-with-the-authoring-set#2"],
  "stale-candidate-frontier": ["validation-checklist#37"],
  "stale-collaboration-fence": ["validation-checklist#6"],
  "state-without-reason": [
    "agent-roles--independence#9",
    "checkpoint--recovery#7",
    "task-model#3",
    "task-model#14",
    "task-model#17",
    "task-model#18",
    "task-model#19",
    "task-model#20",
  ],
  "state-reconciliation-unverified": ["validation-checklist#42"],
  "task-cycle": ["task-model#13"],
  "unattributed-lane-ambiguity": ["validation-checklist#6"],
  "unbounded-task": ["per-task-budgets#1"],
  "unenumerated-change": ["execution-contract#5"],
  "unexecuted-condition": ["specification-to-task-bridge#2", "verification-strategy#10"],
  "ungated-irreversible-operation": ["tool-permission--blast-radius#3"],
  "ungrounded-task": [
    "execution-contract#2",
    "specification-to-task-bridge#1",
    "specification-to-task-bridge#3",
    "specification-to-task-bridge#5",
    "specification-to-task-bridge#6",
    "task-model#1",
    "task-model#13",
    "task-model#15",
  ],
  "unnamed-evaluator": ["agent-roles--independence#1", "agent-roles--independence#7"],
  "unproven-claim": [
    "boundary-with-the-authoring-set#1",
    "boundary-with-the-authoring-set#2",
    "execution-contract#2",
    "per-task-budgets#4",
  ],
  "unproven-property": [
    "verification-strategy#5",
    "verification-strategy#6",
    "verification-strategy#7",
    "verification-strategy#8",
    "verification-strategy#9",
  ],
  "unrecorded-consumption": ["execution-load-budget#2", "per-task-budgets#3", "per-task-budgets#5"],
  "unresumable-run": [
    "checkpoint--recovery#2",
    "checkpoint--recovery#3",
    "checkpoint--recovery#4",
    "checkpoint--recovery#5",
    "checkpoint--recovery#6",
    "checkpoint--recovery#7",
    "task-model#3",
  ],
  "unsurfaced-result": [
    "execution-contract#2",
    "execution-contract#3",
    "execution-contract#6",
    "task-model#12",
    "verification-strategy#2",
    "verification-strategy#4",
  ],
  "unsafe-candidate-target": ["validation-checklist#7"],
  "unreviewed-release-candidate": ["end-to-end-release-lifecycle-protocol#5"],
});

export function findingRuleIds(findingType) {
  return RULE_IDS_BY_FINDING[findingType] ?? [];
}

export function isFindingRulePair(findingType, ruleId) {
  return findingRuleIds(findingType).includes(ruleId);
}
